@startuml
'https://plantuml.com/use-case-diagram

:Administrador: as mA
:Contribuyente: as mC
:Visualizador: as mV

"Crear una coleccion de hechos" as (u1)
"Evaluar solicitud de eliminacion de hecho" as (u2)
"Importar hechos" as (u3)

mA --> (u1)
mA --> (u2)
mA --> (u3)

"Solicitar eliminacion de un hecho" as (u4)
"Agregar hecho" as (u5)
"Ingresar al Sistema" as (u6)

mC --> (u4)
mC --> (u5)
(u4) -.-> (u6) : <<includes>>
(u6) -.-> (u5) : <<extends>>

"Navegar hechos" as (u7)
"Filtrar hechos" as (u8)

mC --> (u7)
mV --> (u7)
mV --> (u5)
(u8) -.-> (u7) : <<extends>>

@enduml