@startuml

node "Fuente Dinámica" {
  component FuenteDinamicaService
  () IFuenteDinamicaService
  FuenteDinamicaService #~~( () IFuenteDinamicaService
}

node "Fuente Estática" {
  component ImportadorService
  () IImportadorService
  ImportadorService #~~( () IImportadorService
}

node "Fuente Proxy" {
  component ProxyService
  () IProxyService
  ProxyService #~~( () IProxyService
}

node "Agregador" {
  component CServicioAgregacion
  component CActualizadorHechosService
  component CHechosService
}

node "Fuente MetaMapa" {
  component FuenteMetaMapaService
  () IFuenteMetaMapaService
  FuenteMetaMapaService #~~( () IFuenteMetaMapaService
}

CServicioAgregacion --> () IFuenteDinamicaService
CServicioAgregacion --> () IImportadorService
CServicioAgregacion --> () IProxyService

ProxyService --> () IFuenteMetaMapaService

CActualizadorHechosService --> CServicioAgregacion
CHechosService --> CActualizadorHechosService

@enduml
